### ISSUE TITLE
Create simple wireframes

### ISSUE THREAD

**Issue by ingdjason** [ARTIIZZ/ARTIIZZ#1]
**Create simple wireframes for your app:**

We recommend using pen and paper for your wireframes as this is the fastest way to get all of your thoughts down on paper. If you'd like to use one of the existing wireframing tools, we've included several links that you can use to develop your wireframes.
Draw out each screen with key elements (input fields, list item display, data shown)
Be sure to identify the core flow between screens within your app
Your app should have at least 3 distinct screens
Add the wireframes to your project repo on Github (either uploading the files or linking to them from the readme)

**Comment by Sandaire** [comment]
Wireframe creates
